global:
  # The smarthost and SMTP sender used for mail notifications.
  smtp_smarthost: 'localhost:25'
  smtp_require_tls: false
  smtp_from: 'Alertmanager'

route:
  receiver: "STEP"
  group_by: ['STEP']
  group_wait:      15s
  group_interval:  15s
  repeat_interval: 1m

receivers:
- name: "STEP"
  webhook_configs:
  - url: 'http://prometheus-msteams:2000/alertmanager'
    send_resolved: true
