version: '3'
services:
  prometheus:
    image: prom/prometheus:latest
    sysctls:
      net.ipv6.conf.all.disable_ipv6: 1
    restart: always
    ports:
      - 127.0.0.1:19090:9090
    volumes:
      - data-prometheus:/etc/prometheus/data
      - ./prometheus:/etc/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--web.external-url=http://${HOSTNAME}:8080/prometheus/'
      - '--web.route-prefix=/prometheus'
    networks:
      - network

  alertmanager:
    image: prom/alertmanager:latest
    sysctls:
      net.ipv6.conf.all.disable_ipv6: 1
    restart: always
    ports:
      - 127.0.0.1:19093:9093
    volumes:
      - ./alertmanager/alertmanager.yml:/prometheus/alertmanager.yml
      - data-prometheus:/data
    command:
      - '--cluster.advertise-address=0.0.0.0:9093'
      - '--config.file=/prometheus/alertmanager.yml'
      - '--storage.path=/data'
      - '--web.external-url=http://${HOSTNAME}:8080/alertmanager/'
      - '--web.route-prefix=/alertmanager'
    networks:
      - network

  nginx:
    image: nginx:latest
    restart: always
    environment:
     - NGINX_HOST=${HOSTNAME}
     - NGINX_PORT=8080
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    command: /bin/bash -c "envsubst '$$NGINX_HOST$$NGINX_PORT' < /etc/nginx/conf.d/reverse_proxy.template > /etc/nginx/conf.d/reverse_proxy.conf && cat /etc/nginx/conf.d/reverse_proxy.conf &&exec nginx -g 'daemon off;'"
    network_mode: "host"

  grafana:
    image: grafana/grafana:latest
    restart: always
    sysctls:
      net.ipv6.conf.all.disable_ipv6: 1
    volumes:
      - data-grafana:/var/lib/grafana
    ports:
      - 127.0.0.1:3000:3000
    networks:
      - network

  loki:
    image: grafana/loki:latest
    restart: always
    sysctls:
      net.ipv6.conf.all.disable_ipv6: 1
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - data-loki:/tmp/loki
    networks:
      - network
 
  promtail:
    image: grafana/promtail:latest
    restart: always
    sysctls:
      net.ipv6.conf.all.disable_ipv6: 1
    ports:
      - 127.0.0.1:2514:1514
    volumes:
      - /var/log:/var/log
      - ./promtail/promtail-syslogconfig.yaml:/etc/promtail/promtail-syslogconfig.yaml
    command: -config.file=/etc/promtail/promtail-syslogconfig.yaml
    networks:
      - network

volumes:
  data-grafana:
    driver: local
  data-prometheus:
    driver: local
  data-loki:
    driver: local

networks:
  network:
